import Header from '../components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins" rel="stylesheet" />
      </head>
      <body>
        <Header />
        {children}
        {/* <Footer/> */}
        <footer className="footer">
          <div className="footer-content">
            <div className="footer-logo">
              <h2>Human Library Cafe</h2>
            </div>
            <div className="footer-links">
              <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/blog">Blog</a></li>
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
              </ul>
            </div>
            <div className="footer-social">
              <ul>
                <li><a href="#"><i className="fab fa-facebook"></i></a></li>
                <li><a href="#"><i className="fab fa-twitter"></i></a></li>
                <li><a href="#"><i className="fab fa-instagram"></i></a></li>
              </ul>
            </div>
          </div>
          <div className="footer-bottom">
            &copy; {new Date().getFullYear()} Human Library Cafe. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  )
}
